-- MySQL Script generated by MySQL Workbench
-- Sat Apr 21 21:09:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sportovisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sportovisko` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nazov` VARCHAR(45) NOT NULL,
  `Cena_za_hodinu` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zakaznik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zakaznik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Meno` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sportovisko_has_Zakaznik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sportovisko_has_Zakaznik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Sportovisko_id` INT NOT NULL,
  `Zakaznik_id` INT NOT NULL,
  `Datum_prenajmu` DATE NOT NULL,
  `Doba_prenajmu` FLOAT NOT NULL,
  `Cas_prenajmu` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `Sportovisko_id`, `Zakaznik_id`),
  INDEX `fk_Športovisko_has_Zakaznik_Zakaznik1_idx` (`Zakaznik_id` ASC),
  INDEX `fk_Športovisko_has_Zakaznik_Športovisko_idx` (`Sportovisko_id` ASC),
  CONSTRAINT `fk_Športovisko_has_Zakaznik_Športovisko`
    FOREIGN KEY (`Sportovisko_id`)
    REFERENCES `mydb`.`Sportovisko` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Športovisko_has_Zakaznik_Zakaznik1`
    FOREIGN KEY (`Zakaznik_id`)
    REFERENCES `mydb`.`Zakaznik` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
